PYTHONPATH=~/tmp/miniconda3/envs/MaProject/bin/python:
[I 2025-02-22 23:08:06,362] A new study created in RDB with name: resnet_wafer_1740262085
[W 2025-02-22 23:08:07,657] Trial 0 failed with parameters: {'lr': 2.191951799792411e-05, 'weight_decay': 6.376878617632343e-06} because of the following error: RuntimeError('Given groups=1, weight of size [64, 3, 7, 7], expected input[64, 1, 224, 224] to have 3 channels, but got 1 channels instead').
Traceback (most recent call last):
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/home/anhcao/tmp/GitHub/DLProject_1/ModelTraining/Wafer-map/Wafer-data-dataset-resize-training.py", line 263, in objective
    best_val_acc, fold_metrics = train_one_fold(
  File "/home/anhcao/tmp/GitHub/DLProject_1/ModelTraining/Wafer-map/Wafer-data-dataset-resize-training.py", line 197, in train_one_fold
    train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)
  File "/home/anhcao/tmp/GitHub/DLProject_1/ModelTraining/Wafer-map/Wafer-data-dataset-resize-training.py", line 83, in train_one_epoch
    outputs = model(inputs)
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/torchvision/models/resnet.py", line 268, in _forward_impl
    x = self.conv1(x)
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
    return F.conv2d(
RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[64, 1, 224, 224] to have 3 channels, but got 1 channels instead
[W 2025-02-22 23:08:07,709] Trial 0 failed with value None.
Loaded configuration:
{'experiment': {'reproducibility': True, 'seed': 42, 'num_trials': 10, 'num_epochs': 10, 'final_epochs': 5, 'save_model': True, 'model_save_path': 'final_model.pth', 'suggest': {'lr': {'low': '1e-5', 'high': '1e-3', 'log': True}, 'weight_decay': {'low': '1e-6', 'high': '1e-2', 'log': True}}}, 'model': {'type': 'resnet50', 'lr': '1e-4', 'weight_decay': '1e-4'}, 'dataset': {'path': '/home/anhcao/tmp/Dataset/Wafermap-dataset/WM811K.pkl'}}
[INFO] Reproducibility enabled. Seed set to 42
[INFO] Using device: cuda
[INFO] Number of classes: 8
[INFO] Classes: ['Center' 'Donut' 'Edge-Loc' 'Edge-Ring' 'Loc' 'Near-full' 'Random'
 'Scratch']
[INFO] Creating Optuna study 'resnet_wafer_1740262085' with DB file: resnet_wafer_v2.db
[INFO] Starting study.optimize with 10 trials...


[OPTUNA] Starting Trial #0 with lr=0.000022, weight_decay=0.000006
[OPTUNA] Trial #0: Starting fold 1/5
[DEBUG] Creating ResNet50 with lr=2.191951799792411e-05, weight_decay=6.376878617632343e-06
[INFO] >>> Starting fold 1 training (Trial #0) for 10 epochs...
Traceback (most recent call last):
  File "/home/anhcao/tmp/GitHub/DLProject_1/ModelTraining/Wafer-map/Wafer-data-dataset-resize-training.py", line 373, in <module>
    main()
  File "/home/anhcao/tmp/GitHub/DLProject_1/ModelTraining/Wafer-map/Wafer-data-dataset-resize-training.py", line 331, in main
    study.optimize(objective, n_trials=num_trials)
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/home/anhcao/tmp/GitHub/DLProject_1/ModelTraining/Wafer-map/Wafer-data-dataset-resize-training.py", line 263, in objective
    best_val_acc, fold_metrics = train_one_fold(
  File "/home/anhcao/tmp/GitHub/DLProject_1/ModelTraining/Wafer-map/Wafer-data-dataset-resize-training.py", line 197, in train_one_fold
    train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)
  File "/home/anhcao/tmp/GitHub/DLProject_1/ModelTraining/Wafer-map/Wafer-data-dataset-resize-training.py", line 83, in train_one_epoch
    outputs = model(inputs)
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/torchvision/models/resnet.py", line 268, in _forward_impl
    x = self.conv1(x)
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/anhcao/tmp/miniconda3/envs/MaProject/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
    return F.conv2d(
RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[64, 1, 224, 224] to have 3 channels, but got 1 channels instead
